@startuml

AppBundle\Manager.SourceManager --> AppBundle\Entity.Project
AppBundle\Manager.SourceManager --> AppBundle\Source.AbstractSource

namespace AppBundle\Manager {
    class SourceManager {
        + {static} fetchNewChanges(project : Project)
        + {static} fetchAllChanges(project : Project)
    }
}

namespace AppBundle\Entity\Source {
    abstract class AbstractSource {
        # id : string
        # options : array
        # project : Project
        + getId() : string
        + getOptions() : array
        + getProject() : Project
        + setProject(project : Project)
        {abstract} + create()
        {abstract} + getFirstChangeExternalId()
        {abstract} + getChangeDetails(changeLogId : int) : array
    }
    class Github extends AbstractSource {
        + changelogUrl : string = 'https://api.github.com/repos/{vendor}/{repository}/commits';
	    + tagsUrl : string = 'https://api.github.com/repos/{vendor}/{repository}/tags';
	    + changelogDetailsUrl : string = 'https://api.github.com/repos/{vendor}/{repository}/commits/{commitId}';

        + create()
        + getFirstChangeExternalId() : string
        + getChangeDetails(changeLogId : int) : array
        - getFromURL(action : string[, options : array]) : Object
        - versions : array
        - getVersions() : array
    }
}

namespace AppBundle\Entity {
    abstract class AbstractEntity {
        # id : int
        # dateAdded : \DateTime
        + getId() : int
        + getDateAdded() : \DateTime
        + onPrePersistSetDateAdded()
    }
    class Asset extends AbstractEntity {
        - title : string
        + getTitle() : string
    }
    class Change extends AbstractEntity {
        - externalId : string {unique}
        - title : string
        - version : string
        - type : string
        - author : string
        + getTitle() : string
        + getVersion() : string
        + getType() : string
        + getCSSClassForType() : string
        + getAuthor() : string
        + getExternalId() : string
        + setTitle(title : string)
        + setVersion(version : string)
        + setType(type : string)
        + setAuthor(author : string)
        + setExternalId(externalId : string)
    }
    class Project extends AbstractEntity {
        - title : string
        - source : string
        - options : array
        - metadata : array
        + getTitle() : string
        + getSource() : string
        + setOptions(array : array)
        + getOptions() : array
        + getMetadata() : array
    }
    class User extends AbstractEntity implements \Symfony\Component\Security\Core\User.UserInterface {
        - username : string
        - email : string
        - password : string
        - roles : array
        + getUsername() : string
        + setUsername(username : string)
        + getEmail() : string
        + setEmail(email : string)
        + getPassword() : string
        + setPassword(password : string)
        + getRoles() : array
        + setRoles(roles : array)
        + getSalt() : null
        + eraseCredentials()
    }

    Change "1" <--> "0..*" Asset
    Project "1" <--> "0..*" Change
}


@enduml