@startuml

namespace AppBundle\Source {
    abstract class AbstractSource {
        {abstract} - changelogUrl : string
        {abstract} + getChangelogs(projectName : string[, lastId : string]) : array
    }
    class Github extends AbstractSource {
        - changelogUrl : string
        + getChangelogUrl(projectName : string) : string
        + getChangelogs([lastId : string]) : array
    }
}

AppBundle\Manager.SourceManager --> AppBundle\Entity.Project
AppBundle\Manager.SourceManager --> AppBundle\Source.AbstractSource

namespace AppBundle\Manager {
    class SourceManager {
        + {static} fetchNewChanges(project : Project, lastId : string)
        + {static} fetchAllChanges(project : Project)
    }
}


namespace AppBundle\Entity {
    abstract class AbstractEntity {
        # id : int
        + getId() : int
    }
    class Asset extends AbstractEntity {
        - title : string
        + getTitle() : string
    }
    class Change extends AbstractEntity {
        - externalId : string
        - title : string
        - version : string
        - type : string
        - author : string
        + getTitle() : string
        + getVersion() : string
        + getType() : string
        + getAuthor() : string
        + getExternalId() : string
        + setTitle(title : string)
        + setVersion(version : string)
        + setType(type : string)
        + setAuthor(author : string)
        + setExternalId(externalId : string)
    }
    class Project extends AbstractEntity {
        - title : string
        - externalId : string
        - source : string
        + getTitle() : string
        + getSource() : string
        + getExternalId() : string
    }
    class User extends AbstractEntity implements \Symfony\Component\Security\Core\User.UserInterface {
        - username : string
        - email : string
        - password : string
        - roles : array
        + getUsername() : string
        + setUsername(username : string)
        + getEmail() : string
        + setEmail(email : string)
        + getPassword() : string
        + setPassword(password : string)
        + getRoles() : array
        + setRoles(roles : array)
        + getSalt() : null
        + eraseCredentials()
    }

    Change "1" --> "0..*" Asset
    Project "1" <--> "0..*" Change
}


@enduml